<?php

$casting_php = array(
array('personnage'=>'Jon Snow ','acteur'=>'Kit Harington'),
array('personnage'=>'Eddard Stark ','acteur'=>'Sean Bean'),
array('personnage'=>'Catelyn Stark ','acteur'=>'Michelle Fairley'),
array('personnage'=>'Robb Stark ','acteur'=>'Richard Madden'),
array('personnage'=>'Sansa Stark ','acteur'=>'Sophie Turner'),
array('personnage'=>'Arya Stark ','acteur'=>'Maisie Williams'),
array('personnage'=>'Bran Stark ','acteur'=>'Isaac Hempstead'),
array('personnage'=>'Rickon Stark ','acteur'=>'Art Parkinson'),
array('personnage'=>'Talisa Maegyr ','acteur'=>'Oona Chaplin'),
array('personnage'=>'Tyrion Lannister ','acteur'=>'Peter Dinklage'),
array('personnage'=>'Tywin Lannister ','acteur'=>'Charles Dance'),
array('personnage'=>'Cersei Lannister ','acteur'=>'Lena Headey'),
array('personnage'=>'Jaime Lannister ','acteur'=>'Nikolaj Coster'),
array('personnage'=>'Lancel Lannister ','acteur'=>'Eugene Simon'),
array('personnage'=>'Daenerys Targaryen ','acteur'=>'Emilia Clarke'),
array('personnage'=>'Viserys Targaryen ','acteur'=>'Harry Lloyd'),
array('personnage'=>'Robert Baratheon ','acteur'=>'Mark Addy'),
array('personnage'=>'Stannis Baratheon ','acteur'=>'Stephen Dillane'),
array('personnage'=>'Renly Baratheon ','acteur'=>'Gethin Anthony'),
array('personnage'=>'Joffrey Baratheon ','acteur'=>'Jack Gleeson'),
array('personnage'=>'Myrcella Baratheon ','acteur'=>'Aimee Richardson'),
array('personnage'=>'Tommen Baratheon ','acteur'=>'Callum Wharry'),
array('personnage'=>'Dean-','acteur'=>'Charles Chapman Victor Quilichini'),
array('personnage'=>'Shireen Baratheon ','acteur'=>'Kerry Ingram'),
array('personnage'=>'Jeor Mormont ','acteur'=>'James Cosmo'),
array('personnage'=>'Jorah Mormont ','acteur'=>'Iain Glen'),
array('personnage'=>'Balon Greyjoy ','acteur'=>'Patrick Malahide'),
array('personnage'=>'Yara Greyjoy ','acteur'=>'Gemma Whelan'),
array('personnage'=>'Theon Greyjoy ','acteur'=>'Alfie Allen'),
array('personnage'=>'Olenna Tyrell ','acteur'=>'Diana Rigg'),
array('personnage'=>'Mace Tyrell ','acteur'=>'Roger Ashton'),
array('personnage'=>'Margaery Tyrell ','acteur'=>'Natalie Dormer'),
array('personnage'=>'Loras Tyrell ','acteur'=>'Finn Jones'),
array('personnage'=>'Davos Mervault ','acteur'=>'Liam Cunningham'),
array('personnage'=>'Matthos Mervault ','acteur'=>'Kerr Logan'),
array('personnage'=>'Walder Frey ','acteur'=>'David Bradley'),
array('personnage'=>'Sandor Clegane ','acteur'=>'Rory McCann'),
array('personnage'=>'Gregor Clegane ','acteur'=>'Conan Stevens'),
array('personnage'=>'Hafthór Júlíus ','acteur'=>'Björnsson'),
array('personnage'=>'Roose Bolton ','acteur'=>'Michael McElhatton'),
array('personnage'=>'Ramsay Bolton ','acteur'=>'Iwan Rheon'),
array('personnage'=>'Brynden Tully ','acteur'=>'Clive Russell'),
array('personnage'=>'Edmure Tully ','acteur'=>'Tobias Menzies'),
array('personnage'=>'Jojen Reed ','acteur'=>'Thomas Sangster'),
array('personnage'=>'Meera Reed ','acteur'=>'Ellie Kendrick'),
array('personnage'=>'Doran Martell ','acteur'=>'Alexander Siddig'),
array('personnage'=>'Oberyn Martell ','acteur'=>'Pedro Pascal'),
array('personnage'=>'Ellaria Sand ','acteur'=>'Indira Varma'),
array('personnage'=>'Trystan Martell ','acteur'=>'Toby Sebastian'),
array('personnage'=>'Obara Martell ','acteur'=>'Keisha Castle'),
array('personnage'=>'Nyméria Sand ','acteur'=>'Jessica Henwick'),
array('personnage'=>'Tyene Sand ','acteur'=>'Rosabell Laurenti Sellers'),
array('personnage'=>'Areo Hotah ','acteur'=>'DeObia Oparei'),
array('personnage'=>'Khal Drogo ','acteur'=>'Jason Momoa'),
array('personnage'=>'Irri Amrita ','acteur'=>'Acharia'),
array('personnage'=>'Doreah Roxanne ','acteur'=>'McKee'),
array('personnage'=>'Missandeï Nathalie ','acteur'=>'Emmanuel'),
array('personnage'=>'Ver Gris ','acteur'=>'Jacob Anderson'),
array('personnage'=>'Daario Naharis ','acteur'=>'Ed Skrein'),
array('personnage'=>'Michiel Huisman ','acteur'=>'Jérémie Covillault'),
array('personnage'=>'Yezzan Enzo ','acteur'=>'Cilenti'),
array('personnage'=>'Samwell Tarly ','acteur'=>'John Bradley-West'),
array('personnage'=>'Pyp Josef ','acteur'=>'Altin Philippe Bozo'),
array('personnage'=>'Grenn Mark ','acteur'=>'Stanley'),
array('personnage'=>'Alliser Thorne ','acteur'=>'Owen Teale'),
array('personnage'=>'Yoren Francis ','acteur'=>'Magee'),
array('personnage'=>'Mestre Aemon ','acteur'=>'Peter Vaughan'),
array('personnage'=>'Janos Slynt ','acteur'=>'Dominic Carter'),
array('personnage'=>'Eddison Tollett ','acteur'=>'Ben Crompton'),
array('personnage'=>'Qhorin Mimain ','acteur'=>'Simon Armstrong'),
array('personnage'=>'Karl Burn ','acteur'=>'Gorman'),
array('personnage'=>'Ygrid Rose ','acteur'=>'Leslie'),
array('personnage'=>'Tormund Kristofer ','acteur'=>'Hivju'),
array('personnage'=>'Vère Hannah ','acteur'=>'Murray'),
array('personnage'=>'Hodor Kristian ','acteur'=>'Nairn'),
array('personnage'=>'Osha Natalia ','acteur'=>'Tena'),
array('personnage'=>'Craster Robert ','acteur'=>'Pugh'),
array('personnage'=>'Mance Rayder ','acteur'=>'Ciarán Hinds'),
array('personnage'=>'Orell Mackenzie ','acteur'=>'Crook'),
array('personnage'=>'Petyr Baelish ','acteur'=>'Aidan Gillen'),
array('personnage'=>'Varys Conleth ','acteur'=>'Hill'),
array('personnage'=>'Mestre Pycelle ','acteur'=>'Julian Glover'),
array('personnage'=>'Mélisandre' ,'acteur'=>'Asshaï Carice van Houten'),
array('personnage'=>'Brienne de ','acteur'=>'Torth Gwendoline Christie'),
array('personnage'=>'Shae Sibel ','acteur'=>'Kekilli'),
array('personnage'=>'Bronn Jerome ','acteur'=>'Flynn'),
array('personnage'=>'Olyvar Will ','acteur'=>'Tudor'),
array('personnage'=>'Mestre Luwin ','acteur'=>'Donald Sumpter'),
array('personnage'=>'Rodrick Cassel ','acteur'=>'Ron Donachie'),
array('personnage'=>'Jory Cassel ','acteur'=>'Jamie Sives'),
array('personnage'=>'Barristan Selmy ','acteur'=>'Ian McElhinney'),
array('personnage'=>'Gendry Joe ','acteur'=>'Dempsie'),
array('personnage'=>'Meryn Trant ','acteur'=>'Ian Beattie'),
array('personnage'=>'Thoros de ','acteur'=>'Myr Paul Kaye'),
array('personnage'=>'Béric Dondarrion ','acteur'=>'Richard Dormer'),
array('personnage'=>'Anguy Philip ','acteur'=>'McGinley'),
array('personnage'=>'Tourte-','acteur'=>'Chaude Ben Hawkey'),
array('personnage'=>'Podrick Payne ','acteur'=>'Daniel Portman'),
array('personnage'=>'Jaqen H ghar','acteur'=> 'Tom Wlaschiha'),
array('personnage'=>'Locke Noah ','acteur'=>'Taylor'),
array('personnage'=>'Hizdahr zo ','acteur'=>'Loraq Joel Fry')
);